// Computer_System_mm_interconnect_2.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module Computer_System_mm_interconnect_2 (
		input  wire        System_PLL_sys_clk_clk,                         //                       System_PLL_sys_clk.clk
		input  wire        module2sdram_reset_reset_bridge_in_reset_reset, // module2sdram_reset_reset_bridge_in_reset.reset
		input  wire [4:0]  module2sdram_read_master_address,               //                 module2sdram_read_master.address
		output wire        module2sdram_read_master_waitrequest,           //                                         .waitrequest
		input  wire        module2sdram_read_master_chipselect,            //                                         .chipselect
		input  wire        module2sdram_read_master_read,                  //                                         .read
		output wire [31:0] module2sdram_read_master_readdata,              //                                         .readdata
		output wire        module2sdram_read_master_readdatavalid,         //                                         .readdatavalid
		output wire [0:0]  m2s_fifo_out_address,                           //                             m2s_fifo_out.address
		output wire        m2s_fifo_out_read,                              //                                         .read
		input  wire [31:0] m2s_fifo_out_readdata,                          //                                         .readdata
		input  wire        m2s_fifo_out_waitrequest                        //                                         .waitrequest
	);

	wire         module2sdram_read_master_translator_avalon_universal_master_0_waitrequest;   // m2s_fifo_out_translator:uav_waitrequest -> module2sdram_read_master_translator:uav_waitrequest
	wire  [31:0] module2sdram_read_master_translator_avalon_universal_master_0_readdata;      // m2s_fifo_out_translator:uav_readdata -> module2sdram_read_master_translator:uav_readdata
	wire         module2sdram_read_master_translator_avalon_universal_master_0_debugaccess;   // module2sdram_read_master_translator:uav_debugaccess -> m2s_fifo_out_translator:uav_debugaccess
	wire   [4:0] module2sdram_read_master_translator_avalon_universal_master_0_address;       // module2sdram_read_master_translator:uav_address -> m2s_fifo_out_translator:uav_address
	wire         module2sdram_read_master_translator_avalon_universal_master_0_read;          // module2sdram_read_master_translator:uav_read -> m2s_fifo_out_translator:uav_read
	wire   [3:0] module2sdram_read_master_translator_avalon_universal_master_0_byteenable;    // module2sdram_read_master_translator:uav_byteenable -> m2s_fifo_out_translator:uav_byteenable
	wire         module2sdram_read_master_translator_avalon_universal_master_0_readdatavalid; // m2s_fifo_out_translator:uav_readdatavalid -> module2sdram_read_master_translator:uav_readdatavalid
	wire         module2sdram_read_master_translator_avalon_universal_master_0_lock;          // module2sdram_read_master_translator:uav_lock -> m2s_fifo_out_translator:uav_lock
	wire         module2sdram_read_master_translator_avalon_universal_master_0_write;         // module2sdram_read_master_translator:uav_write -> m2s_fifo_out_translator:uav_write
	wire  [31:0] module2sdram_read_master_translator_avalon_universal_master_0_writedata;     // module2sdram_read_master_translator:uav_writedata -> m2s_fifo_out_translator:uav_writedata
	wire   [2:0] module2sdram_read_master_translator_avalon_universal_master_0_burstcount;    // module2sdram_read_master_translator:uav_burstcount -> m2s_fifo_out_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (5),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (5),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (1),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) module2sdram_read_master_translator (
		.clk                    (System_PLL_sys_clk_clk),                                                      //                       clk.clk
		.reset                  (module2sdram_reset_reset_bridge_in_reset_reset),                              //                     reset.reset
		.uav_address            (module2sdram_read_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (module2sdram_read_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (module2sdram_read_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (module2sdram_read_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (module2sdram_read_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (module2sdram_read_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (module2sdram_read_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (module2sdram_read_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (module2sdram_read_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (module2sdram_read_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (module2sdram_read_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (module2sdram_read_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (module2sdram_read_master_waitrequest),                                        //                          .waitrequest
		.av_chipselect          (module2sdram_read_master_chipselect),                                         //                          .chipselect
		.av_read                (module2sdram_read_master_read),                                               //                          .read
		.av_readdata            (module2sdram_read_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (module2sdram_read_master_readdatavalid),                                      //                          .readdatavalid
		.av_burstcount          (1'b1),                                                                        //               (terminated)
		.av_byteenable          (4'b1111),                                                                     //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                        //               (terminated)
		.av_begintransfer       (1'b0),                                                                        //               (terminated)
		.av_write               (1'b0),                                                                        //               (terminated)
		.av_writedata           (32'b00000000000000000000000000000000),                                        //               (terminated)
		.av_lock                (1'b0),                                                                        //               (terminated)
		.av_debugaccess         (1'b0),                                                                        //               (terminated)
		.uav_clken              (),                                                                            //               (terminated)
		.av_clken               (1'b1),                                                                        //               (terminated)
		.uav_response           (2'b00),                                                                       //               (terminated)
		.av_response            (),                                                                            //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                        //               (terminated)
		.av_writeresponsevalid  ()                                                                             //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (1),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (5),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (1),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) m2s_fifo_out_translator (
		.clk                    (System_PLL_sys_clk_clk),                                                      //                      clk.clk
		.reset                  (module2sdram_reset_reset_bridge_in_reset_reset),                              //                    reset.reset
		.uav_address            (module2sdram_read_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (module2sdram_read_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (module2sdram_read_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (module2sdram_read_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (module2sdram_read_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (module2sdram_read_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (module2sdram_read_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (module2sdram_read_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (module2sdram_read_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (module2sdram_read_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (module2sdram_read_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (m2s_fifo_out_address),                                                        //      avalon_anti_slave_0.address
		.av_read                (m2s_fifo_out_read),                                                           //                         .read
		.av_readdata            (m2s_fifo_out_readdata),                                                       //                         .readdata
		.av_waitrequest         (m2s_fifo_out_waitrequest),                                                    //                         .waitrequest
		.av_write               (),                                                                            //              (terminated)
		.av_writedata           (),                                                                            //              (terminated)
		.av_begintransfer       (),                                                                            //              (terminated)
		.av_beginbursttransfer  (),                                                                            //              (terminated)
		.av_burstcount          (),                                                                            //              (terminated)
		.av_byteenable          (),                                                                            //              (terminated)
		.av_readdatavalid       (1'b0),                                                                        //              (terminated)
		.av_writebyteenable     (),                                                                            //              (terminated)
		.av_lock                (),                                                                            //              (terminated)
		.av_chipselect          (),                                                                            //              (terminated)
		.av_clken               (),                                                                            //              (terminated)
		.uav_clken              (1'b0),                                                                        //              (terminated)
		.av_debugaccess         (),                                                                            //              (terminated)
		.av_outputenable        (),                                                                            //              (terminated)
		.uav_response           (),                                                                            //              (terminated)
		.av_response            (2'b00),                                                                       //              (terminated)
		.uav_writeresponsevalid (),                                                                            //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                         //              (terminated)
	);

endmodule
